#!/usr/bin/env sh

# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

# Exclude all applications except Alacritty and Firefox from
yabai -m rule \
  --add app!="^(Alacritty|Firefox Developer Edition|ChatGPT)$" manage=off
yabai -m rule --apply

# Global settings
yabai -m config                               \
  debug_output                 off            \
  focus_follows_mouse          autofocus      \
  display_arrangement_order     default        \
  window_origin_display        default        \
  window_placement             second_child   \
  window_zoom_persist          on             \
  insert_feedback_color        0xff83a598     \
  split_ratio                  0.66666666     \
  split_type                   auto           \
  mouse_modifier               ctrl           \
  mouse_action1                move           \
  mouse_action2                resize         \
  mouse_drop_action            swap

# Space settings
yabai -m config                               \
  layout                       bsp            \
  top_padding                  30             \
  bottom_padding               30             \
  left_padding                 20             \
  right_padding                20             \
  window_gap                   05             \
  auto_balance                 on             \

echo "yabai configuration loaded"
