tap "koekeishiya/formulae"

# GNU programs to replace the BSD ones
brew "binutils"
brew "coreutils"
brew "diffutils"
brew "ed"
brew "findutils"
brew "gawk"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "grep"
brew "gzip"
brew "screen"

# GNU programs existing in macOS but with outdated versions
brew "bash"
brew "bison"
brew "make"
brew "zsh"

# Other programs
brew "bash-language-server"
brew "curl"
brew "fzf"
brew "git"
brew "gnupg"
brew "grpcurl"
brew "htop"
brew "jq"
brew "koekeishiya/formulae/yabai"
brew "mold"
brew "neovim"
brew "openssl@3"
brew "shellcheck"
brew "telnet"
brew "tmux"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "docker-desktop"
cask "firefox@developer-edition"
cask "font-hack-nerd-font"
cask "hammerspoon"
cask "karabiner-elements"
